const projects = [
  {
    id: 1,
    title: "Mystry Message",
    description:
      "An anonymous messaging web app that allows users to send and receive secret messages with a clean, interactive UI.",
    image: "/mystry-message.png",
    category: "web",
    tags: [
      "Next.js",
      "Tailwind CSS",
      "TypeScript",
      "Shadcn",
      "Nodemailer",
      "Next auth",
      "App Router",
    ],
    codeUrl: "https://github.com/AmmarMubashir/mystry-message",
    demoUrl: "https://mystry-message-dun.vercel.app/",
  },

  {
    id: 2,
    title: "Rawaan Pakistan",
    description:
      "A travel and tourism platform with an interactive user experience.",
    image: "/rawaan.png",
    category: "web",
    tags: ["Next.js", "Tailwind CSS", "CSS", "Material UI"],
    codeUrl: "https://github.com/AmmarMubashir/Rawaan-Pakistan",
    demoUrl: "https://rawaan-pakistan.vercel.app/",
  },
  {
    id: 3,
    title: "SoftDesk V2",
    description:
      "An enhanced version of the SoftDesk platform for managing projects and teams.",
    image: "/softdesk.png",
    category: "web",
    tags: ["Next.js", "Tailwind CSS"],
    codeUrl: "https://github.com/AmmarMubashir/SoftdeskV2",
    demoUrl: "https://softdesk-v2.vercel.app/",
  },
  {
    id: 4,
    title: "Apona",
    description:
      "A modern web application for seamless online transactions and digital management.",
    image: "/apona.png",
    category: "web",
    tags: ["HTML", "CSS", "Bootstrap"],
    codeUrl: "https://github.com/AmmarMubashir/Apona",
    demoUrl: "https://apona.vercel.app/",
  },
  {
    id: 5,
    title: "Affonso Landing Page",
    description:
      "A sleek and responsive SaaS affiliate program landing page designed to drive conversions. Built with modern UI components and smooth animations to deliver an engaging user experience.",
    image: "/affonso.png",
    category: "web",
    tags: ["Next.js", "Tailwind CSS", "Shadcn", "Framer Motion"],
    codeUrl: "https://github.com/AmmarMubashir/Affonso",
    demoUrl: "https://affonso-zeta.vercel.app/",
  },
  {
    id: 6,
    title: "TechBuzzLab",
    description:
      "A low-code web solution for rapid application development and deployment.",
    image: "/techbuzz.png",
    category: "web",
    tags: ["Next.js", "Tailwind CSS", "Calendly"],
    codeUrl: "https://github.com/AmmarMubashir/low-code",
    demoUrl: "https://low-code-puce.vercel.app/",
  },
  {
    id: 7,
    title: "Gantry",
    description:
      "A web-based platform for managing and automating industrial workflows.",
    image: "/gantry.png",
    category: "web",
    tags: ["Next.js", "Tailwind CSS"],
    codeUrl: "https://github.com/AmmarMubashir/Gantry-web",
    demoUrl: "https://gantry-web.vercel.app/",
  },
  {
    id: 8,
    title: "Claims Crafter",
    description:
      "A claims management system designed for insurance and legal services.",
    image: "/claimscrafter.png",
    category: "web",
    tags: ["React", "CSS"],
    codeUrl: "https://github.com/AmmarMubashir/claimscrafter",
    demoUrl: "https://claimscrafter.vercel.app/",
  },
  {
    id: 9,
    title: "Expense Tracker",
    description:
      "A personal finance management tool to track income and expenses.",
    image: "/expense-tracker.png",
    category: "web",
    tags: ["Next.js", "Neon DB", "Tailwind CSS"],
    codeUrl: "https://github.com/AmmarMubashir/next_expense_tracker",
    demoUrl: "https://expense-tracker-sooty-five.vercel.app/",
  },
  {
    id: 10,
    title: "Mini Calendar Watch",
    description:
      "A simple calendar watch application with date and time functionality.",
    image: "/mini-calendar.png",
    category: "web",
    tags: ["HTML", "CSS", "JavaScript"],
    codeUrl: "https://github.com/AmmarMubashir/MiniCalendarWatch",
    demoUrl: "https://mini-calendar-watch.vercel.app/",
  },
  {
    id: 11,
    title: "Weather App",
    description:
      "A weather forecasting app providing real-time weather updates.",
    image: "/weather.png",
    category: "web",
    tags: ["HTML", "OpenWeather API", "CSS", "JavaScript"],
    codeUrl: "https://github.com/AmmarMubashir/weatherApp",
    demoUrl: "https://weather-app-alpha-lovat.vercel.app/",
  },
  {
    id: 12,
    title: "Food Website",
    description:
      "A modern and responsive food website showcasing different cuisines.",
    image: "/food.png",
    category: "web",
    tags: ["HTML", "CSS", "JavaScript"],
    codeUrl: "https://github.com/AmmarMubashir/foodwebsite",
    demoUrl: "https://foodwebsite-phi-seven.vercel.app/",
  },
  {
    id: 13,
    title: "Coffee Web",
    description: "A coffee-themed web page with an elegant UI and animations.",
    image: "/coffe.png",
    category: "web",
    tags: ["HTML", "CSS", "JavaScript"],
    codeUrl: "https://github.com/AmmarMubashir/coffe-web",
    demoUrl: "https://coffe-web-alpha.vercel.app/",
  },
  {
    id: 14,
    title: "Ammar Portfolio",
    description:
      "A personal portfolio website to showcase projects and experience.",
    image: "/ammar-portfolio.png",
    category: "portfolio",
    tags: ["HTML", "CSS", "JavaScript"],
    codeUrl: "https://github.com/AmmarMubashir/ammar-portfolio",
    demoUrl: "https://ammar-portfolio-six.vercel.app/",
  },
  {
    id: 15,
    title: "Cloned Portfolio",
    description:
      "A portfolio website cloned with improved design and animations.",
    image: "/cloned-portfolio.png",
    category: "portfolio",
    tags: ["React", "CSS", "AOS animation"],
    codeUrl: "https://github.com/AmmarMubashir/cloned-portfolio",
    demoUrl: "https://cloned-portfolio-psi.vercel.app/",
  },
  {
    id: 16,
    title: "Random Joke Generator",
    description: "A fun web app that generates random jokes using an API.",
    image: "/random-joke.png",
    category: "fun",
    tags: ["HTML", "JavaScript", "API"],
    codeUrl: "https://github.com/AmmarMubashir/Random-joke-generator",
    demoUrl: "https://random-joke-generator-eight-murex.vercel.app/",
  },
  {
    id: 17,
    title: "Zeeo World",
    description:
      "A futuristic web project featuring an innovative digital experience.",
    image: "/zeeo-world.png",
    category: "web",
    tags: ["React", "Tailwind CSS"],
    codeUrl: "https://github.com/AmmarMubashir/zeeoWorld",
    demoUrl: "https://zeeo-world.vercel.app/",
  },
  {
    id: 18,
    title: "Web Me",
    description: "A personal branding website with interactive UI elements.",
    image: "/web-me.png",
    category: "portfolio",
    tags: ["React", "CSS"],
    codeUrl: "https://github.com/AmmarMubashir/web-me",
    demoUrl: "https://web-me-seven.vercel.app/",
  },
  {
    id: 19,
    title: "Portfolio Sample",
    description:
      "A sample portfolio website with modern design and responsiveness.",
    image: "/portfolio-sample.png",
    category: "portfolio",
    tags: ["HTML", "Tailwind CSS"],
    codeUrl: "https://github.com/AmmarMubashir/portfolio-sample",
    demoUrl: "https://portfolio-sample-tan.vercel.app/",
  },
];

export default projects;
